url: https://www.wjlsteelstructure.com

title: WANJINLONG

keywords: steel structure

description: WANJINLONG

address: Huanhu Community, Zhangjiawan Town, Tongzhou District, Beijing, China

tel1: +86-13911672860

tel2: +86-010-61509657

fax: +86-010-61509650

email: duo@wjlsteelstructure.com

facebook: https://www.facebook.com/steelstructurestorage

twitter: https://twitter.com/wjlprefabhomes

linkedin: https://www.linkedin.com/in/steelstructurewarehouse/

exclude:
  - README.md
  - style.css
